// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVAY6BUowhZysAoNQdTqGuZo7YKfY86IQ',
    appId: '1:707694938222:web:e49b44ff024d6bbedd3e7f',
    messagingSenderId: '707694938222',
    projectId: 'e-commerce-app-fbffd',
    authDomain: 'e-commerce-app-fbffd.firebaseapp.com',
    storageBucket: 'e-commerce-app-fbffd.appspot.com',
    measurementId: 'G-YRXZ55S104',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiA6vgom2n2sYE3uONyQAGxH1CBP9HQyk',
    appId: '1:707694938222:android:3012115acc5a7e4edd3e7f',
    messagingSenderId: '707694938222',
    projectId: 'e-commerce-app-fbffd',
    storageBucket: 'e-commerce-app-fbffd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuVKg_h4MfXUp2oUIdiY7mZ1dRLOcbOrI',
    appId: '1:707694938222:ios:adafd7ae24d79195dd3e7f',
    messagingSenderId: '707694938222',
    projectId: 'e-commerce-app-fbffd',
    storageBucket: 'e-commerce-app-fbffd.appspot.com',
    iosBundleId: 'com.example.eCommerceAppWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVAY6BUowhZysAoNQdTqGuZo7YKfY86IQ',
    appId: '1:707694938222:web:484923d498496b20dd3e7f',
    messagingSenderId: '707694938222',
    projectId: 'e-commerce-app-fbffd',
    authDomain: 'e-commerce-app-fbffd.firebaseapp.com',
    storageBucket: 'e-commerce-app-fbffd.appspot.com',
    measurementId: 'G-QBX11PLKK6',
  );
}
